### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by archanpatkar** [VasishthaFramework/Core#3]
### Creating the Foundation for the Framework

- [x] Front Controller
- [x] Controllers
- [x] Static Serving
- [x]  Inter Controller Communication
- [x] Dynamic Static Serving
- [x] Views
- [x] Templating Views using **ejs** (Dynamic HTML Rendering)
- [ ] Session Management
- [ ] Filters
- [ ] Models
